<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_concat(id(, , icon-close-button-1454703945249, , ))_icon-close-button-1454703945249</name>
   <tag></tag>
   <elementGuidId>bb2a66cd-2512-4234-87ca-be4fb4fad4be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='icon-close-button-1454703945249']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icon-close-button-1454703945249</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e17c51b6-7086-448f-ba84-ca775de72652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times element-close-button</value>
      <webElementGuid>5976cd09-8020-4d74-ba87-f6679fd3117a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon-close-button-1454703945249</value>
      <webElementGuid>eec2d163-e8b5-417f-ab65-e0b9d28804dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon-close-button-1454703945249&quot;)</value>
      <webElementGuid>578f65cc-110c-4e65-956b-0271bca2e929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/telkom/Page_Beranda  Telkomsel/iframe__sp-fancybox-iframe sp-fancybox-skin sp-fancybox-iframe-410 adaptive-resolution</value>
      <webElementGuid>4ac1bddc-81d2-4420-8b58-15e0a0532506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='icon-close-button-1454703945249']</value>
      <webElementGuid>b506bd45-4e55-4af6-b317-cf55c50e1aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='close-button-1454703945249']/i</value>
      <webElementGuid>affd44ee-5f1f-4701-ac64-cb336d599e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>9990c859-341f-42fc-af09-40391a6f77c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'icon-close-button-1454703945249']</value>
      <webElementGuid>a5ff0801-d16a-4a11-a612-b76c27ef8030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
