<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Keluar_menu-mobile</name>
   <tag></tag>
   <elementGuidId>585869f4-38ef-486f-b93c-b8101621f8ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='burger-nav-mobile']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.menu-mobile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fdcb3e31-80a6-43f8-9292-934a87cfa80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/../themes/custom/telkomsel/assets/img/revamp/header/burger-menu-icon.svg</value>
      <webElementGuid>7ec43467-6139-40fb-bb3e-bf68f068dd1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Telkomsel</value>
      <webElementGuid>70c47851-c9c0-4692-8d53-3bcd7d7cdc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-mobile</value>
      <webElementGuid>6e2ba7f0-f79c-4bd2-bd07-80dbfcd28b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;burger-nav-mobile&quot;)/img[@class=&quot;menu-mobile&quot;]</value>
      <webElementGuid>d522cb7e-6ac8-48f9-8f03-626a71ad5575</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='burger-nav-mobile']/img</value>
      <webElementGuid>5575d5b3-48b1-43e0-93a5-e86d0b74371d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Telkomsel'])[2]</value>
      <webElementGuid>ab59852c-e308-4b3c-85a2-2127a5a4ed6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/a[2]/img</value>
      <webElementGuid>aec54b12-1a8f-4a31-85ce-0a88bc9fc74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/../themes/custom/telkomsel/assets/img/revamp/header/burger-menu-icon.svg' and @alt = 'Telkomsel']</value>
      <webElementGuid>92d9cda9-c570-4d70-b06e-2e827a6c85c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
