<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>5f7f2c20-43a9-4ccd-89f1-6582409b04f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='be-navigation-mobile']/div[3]/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd1297d7-13e3-4802-a30f-2803a38ea4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://gitlab.com/users/sign_up/</value>
      <webElementGuid>a1fdac96-ebac-4154-bd46-7bb4e2b3c5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>d36b1a97-aa0e-4fb0-8031-39bde4072238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slp-btn nav-menu_icon slp-btn-ghost</value>
      <webElementGuid>03e04499-8c07-4c77-9306-30c2eb920705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Register </value>
      <webElementGuid>d2e78299-87f5-4a37-bdfa-e0c506731c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be-navigation-mobile&quot;)/div[@class=&quot;nav-menu&quot;]/div[1]/ul[1]/li[2]/a[@class=&quot;slp-btn nav-menu_icon slp-btn-ghost&quot;]</value>
      <webElementGuid>7bbe8fcf-0813-4676-9364-a1d70726da4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='be-navigation-mobile']/div[3]/div/ul/li[2]/a</value>
      <webElementGuid>527ff8ca-4a27-46a0-8999-e5cb6368e88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Register')])[2]</value>
      <webElementGuid>69d4638c-4f42-4afb-86a8-823189eb72b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::a[1]</value>
      <webElementGuid>b7bef66d-8f4b-4692-b2a9-2a5efa03db42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[2]/following::a[2]</value>
      <webElementGuid>849d5b13-bbf5-4368-b268-0f5f945e713f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>11a150ae-c6e8-4fd2-b226-3487821c787b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Talk to an expert'])[3]/preceding::a[1]</value>
      <webElementGuid>92b1fc9e-004a-4e88-97cf-4779b2d081da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://gitlab.com/users/sign_up/')])[3]</value>
      <webElementGuid>c71a1544-4da5-40c0-9129-d1cbd6f0a221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[2]/a</value>
      <webElementGuid>cc268214-709f-45f8-83b9-e7589344060d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://gitlab.com/users/sign_up/' and (text() = ' Register ' or . = ' Register ')]</value>
      <webElementGuid>10a40493-b5fc-49d9-b0b6-720e435735ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
