<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Switch to GitLab Next_header-user-dropdown-toggle</name>
   <tag></tag>
   <elementGuidId>e6909b54-fb8d-41a9-9025-dcf7873934af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch to GitLab Next'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.header-user-dropdown-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>45467bfe-36af-477c-aa66-52da86c8c219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-user-dropdown-toggle</value>
      <webElementGuid>faa6ef16-2f09-4120-b949-7c4f868f15be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>acce904f-f798-41b3-93bc-0bd70b801ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/LourenFermando</value>
      <webElementGuid>9267991b-5576-4b08-8ca4-47915c8a12af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ui-indigo tab-width-8 gl-browser-chrome gl-platform-windows page-initialised&quot;]/header[@class=&quot;navbar navbar-gitlab navbar-expand-sm js-navbar&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;header-content js-header-content&quot;]/div[@class=&quot;navbar-collapse gl-transition-medium collapse&quot;]/ul[@class=&quot;nav navbar-nav gl-w-full&quot;]/li[@class=&quot;nav-item header-user js-nav-user-dropdown dropdown&quot;]/a[@class=&quot;header-user-dropdown-toggle&quot;]</value>
      <webElementGuid>458a1670-cb60-4526-8085-e2f3b28a1c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch to GitLab Next'])[1]/following::a[1]</value>
      <webElementGuid>b4237925-79e9-464f-9784-f83415b3e345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contribute to GitLab'])[1]/following::a[2]</value>
      <webElementGuid>736732b9-8f74-47b5-be73-ccbe67242805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LourenFermando'])[1]/preceding::a[1]</value>
      <webElementGuid>96488711-d03b-474d-ad8e-d11dbba8d439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/LourenFermando')]</value>
      <webElementGuid>4c144e8d-3a0f-4138-8d33-67e673b57567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>e2c15085-729c-4b14-b8a8-c76e5270fac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/LourenFermando']</value>
      <webElementGuid>fbcb9e7c-09fc-405e-9da3-ee207fa4a21f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
