<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign out</name>
   <tag></tag>
   <elementGuidId>5f992944-3ef9-4be6-a802-47225c403b85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Sign out')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sign-out-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e1b5eef-bb61-4aad-943b-f2de8ad7f709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign-out-link</value>
      <webElementGuid>58dac0ff-3a2e-4707-a638-02ef3e8256f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-selector</name>
      <type>Main</type>
      <value>sign_out_link</value>
      <webElementGuid>6ed2ad72-95bf-467c-bfa9-e3a88d2dd669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>56cddec1-fcc6-42d1-a091-2eba17986055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>2924b0fd-ae17-4572-bd61-6d8a8cf430a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/users/sign_out</value>
      <webElementGuid>d267151d-3864-4eeb-a712-01b8d4142ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign out</value>
      <webElementGuid>d9cf71b4-3e86-4f78-b1a5-3b720beb74e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ui-indigo tab-width-8 gl-browser-chrome gl-platform-windows page-initialised&quot;]/header[@class=&quot;navbar navbar-gitlab navbar-expand-sm js-navbar&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;header-content js-header-content&quot;]/div[@class=&quot;navbar-collapse gl-transition-medium collapse&quot;]/ul[@class=&quot;nav navbar-nav gl-w-full&quot;]/li[@class=&quot;nav-item header-user js-nav-user-dropdown dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right show&quot;]/ul[1]/li[14]/a[@class=&quot;sign-out-link&quot;]</value>
      <webElementGuid>e97c3e86-a0ee-44dc-8529-21eb50d3033d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign out')]</value>
      <webElementGuid>a8b82aef-040c-4a29-a46f-91f9b2371da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch to GitLab Next'])[2]/following::a[1]</value>
      <webElementGuid>a14c7241-acbc-4770-8042-6e9dcca3fb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contribute to GitLab'])[2]/following::a[2]</value>
      <webElementGuid>0b22e55c-3ab7-4ac0-8d90-a867e2482c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/preceding::a[1]</value>
      <webElementGuid>bf7b1e40-fe33-481b-ba47-e6fffe4a0253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::a[1]</value>
      <webElementGuid>69502e26-1e91-44ac-81ed-9ab264b3e654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign out']/parent::*</value>
      <webElementGuid>8adbba7e-10b8-4c33-b973-f456f18feb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/users/sign_out')]</value>
      <webElementGuid>1b12b54d-ad7a-4030-9eb1-cecf9a21776b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[14]/a</value>
      <webElementGuid>b488a7a8-68b2-4e40-af9c-dd8e384a20a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/users/sign_out' and (text() = 'Sign out' or . = 'Sign out')]</value>
      <webElementGuid>512a2496-6dce-424a-a204-17e1bc8b83dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
