<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-  How to reach me_btn btn-primary</name>
   <tag></tag>
   <elementGuidId>1195b307-eccd-4e74-b45b-8beb9c194128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Continue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad64e54f-2788-4bd8-844f-b910cb92c7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>eabc4842-41ae-4505-91e6-8fb41eeafce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hydro-click</name>
      <type>Main</type>
      <value>{&quot;event_type&quot;:&quot;dashboard.click&quot;,&quot;payload&quot;:{&quot;event_context&quot;:&quot;PROFILE_README_BANNER&quot;,&quot;dashboard_context&quot;:&quot;user&quot;,&quot;dashboard_version&quot;:2,&quot;target&quot;:&quot;CREATE_PROFILE_README&quot;,&quot;originating_url&quot;:&quot;https://github.com/dashboard-feed&quot;,&quot;user_id&quot;:105488838}}</value>
      <webElementGuid>940b2a7d-4f46-45a7-acfa-c4af16915896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hydro-click-hmac</name>
      <type>Main</type>
      <value>f28c1f04be90e77efc666a3393576db750a11c2df0dd0dde81ccfdcefb4dc80d</value>
      <webElementGuid>f71ad0e0-3fed-4d90-8259-bda8f3e06f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-optimizely-hydro-click</name>
      <type>Main</type>
      <value>{&quot;event_type&quot;:&quot;optimizely.track&quot;,&quot;payload&quot;:{&quot;event_name&quot;:&quot;click.cta_create_readme&quot;,&quot;enrollment_id&quot;:&quot;a9efa993ecca27f8344a3d4585db059d&quot;,&quot;attributes&quot;:{},&quot;tags&quot;:{&quot;location&quot;:&quot;introduce yourself&quot;},&quot;originating_url&quot;:&quot;https://github.com/dashboard-feed&quot;,&quot;user_id&quot;:105488838}}</value>
      <webElementGuid>4d5caac8-de04-4202-ab0f-ff5398bfac34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-optimizely-hydro-click-hmac</name>
      <type>Main</type>
      <value>ae6b7638eb674bd8c4891b07ebb8ea478bd511f5dc2c4c7602b9cfdf20446db8</value>
      <webElementGuid>8a5b00ec-6c13-4dad-bb5f-160e190003a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d9b7ef64-ae1a-4694-8eb6-b5c1b5a5d43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>5217b197-db12-41ec-96a2-28530b26cf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-1&quot;)/div[@class=&quot;Box mt-3 js-notice&quot;]/div[@class=&quot;Box-body&quot;]/div[@class=&quot;mt-2 d-flex flex-items-center flex-justify-end&quot;]/form[@class=&quot;button_to&quot;]/input[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>38f999ec-d993-460a-acd1-6d427ff99097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Continue']</value>
      <webElementGuid>20659e43-329f-48b9-8a46-f572747ba0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-1']/div/div/div[3]/form[2]/input</value>
      <webElementGuid>e5bd54a5-047d-4a4d-bef5-68ff64ac2044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/input</value>
      <webElementGuid>2dbce425-d523-4378-99d5-19cbb8cf3888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>f794bde0-ad89-4518-b8b4-9310ab4b78e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
