<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign out</name>
   <tag></tag>
   <elementGuidId>094b0059-3a80-4fab-8310-e484707de051</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Sign out')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sign-out-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a62a776d-0407-4a6c-8dc5-6c8578b6a996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign-out-link</value>
      <webElementGuid>f0e6774b-2293-4968-86d6-21ff4be47c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-selector</name>
      <type>Main</type>
      <value>sign_out_link</value>
      <webElementGuid>fd26494e-a296-4de9-a033-d18e0e8881ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>29160e87-0a72-47e8-a8e0-97ca143c37fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>905ff4e6-2fbf-4a40-9e31-349f08a2923f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/users/sign_out</value>
      <webElementGuid>9c3bc055-5e7d-477c-90c4-a50957b5292d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign out</value>
      <webElementGuid>90994f86-e2ab-4c3e-abb2-846de1df784b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ui-indigo tab-width-8 gl-browser-chrome gl-platform-windows page-initialised&quot;]/header[@class=&quot;navbar navbar-gitlab navbar-expand-sm js-navbar&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;header-content js-header-content&quot;]/div[@class=&quot;navbar-collapse gl-transition-medium collapse&quot;]/ul[@class=&quot;nav navbar-nav gl-w-full&quot;]/li[@class=&quot;nav-item header-user js-nav-user-dropdown dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right show&quot;]/ul[1]/li[14]/a[@class=&quot;sign-out-link&quot;]</value>
      <webElementGuid>52172a7f-d4c0-42f0-af0e-fcd5dd0008d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign out')]</value>
      <webElementGuid>f6429edf-42ab-480d-90c7-02e14b6e4f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch to GitLab Next'])[2]/following::a[1]</value>
      <webElementGuid>917e6f4d-68a9-43c3-af4a-6d80bd7ddf43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contribute to GitLab'])[2]/following::a[2]</value>
      <webElementGuid>f3105d6b-cb24-477c-b834-52a3ec2e4d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/preceding::a[1]</value>
      <webElementGuid>ea50928b-fca7-46e9-925f-c0f318242541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::a[1]</value>
      <webElementGuid>de22344d-60ea-4f53-8c80-0fab7c1b22ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign out']/parent::*</value>
      <webElementGuid>28c55b3d-4e7a-45bd-9d89-521bc5f127a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/users/sign_out')]</value>
      <webElementGuid>8fd195f8-e3cb-485d-94d0-5e1a4c8a592f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[14]/a</value>
      <webElementGuid>86e37f2d-5b81-481d-b370-0180ba413316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/users/sign_out' and (text() = 'Sign out' or . = 'Sign out')]</value>
      <webElementGuid>8fca64f0-f15d-4fe6-866d-589d44dfca04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
