<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_commit</name>
   <tag></tag>
   <elementGuidId>e7464f5a-f9c7-4cb7-99f5-ea02846a99f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='commit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;commit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>279cd9f1-7a03-45d5-91f1-ea2945f54542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>42407b10-9b49-4811-85e8-9325ac63f286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commit</value>
      <webElementGuid>70985eb9-4cb5-4f6d-83e5-a87f215a3e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>b53f631f-b33d-4fbb-8e6c-098c38413058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block js-sign-in-button</value>
      <webElementGuid>6c598dec-074b-429a-80b1-da6c02edd722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disable-with</name>
      <type>Main</type>
      <value>Signing in…</value>
      <webElementGuid>2d2c7532-bb86-4561-90a9-d5ba68d7963d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-signin-label</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>22afe828-e087-4922-ad33-5898cccb8db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sso-label</name>
      <type>Main</type>
      <value>Sign in with your identity provider</value>
      <webElementGuid>b46ff816-51b6-4cb1-8ce4-89953f540691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>development</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2fe9980b-eb78-4665-8346-c43c9f4224af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/div[@class=&quot;auth-form-body mt-3&quot;]/form[1]/div[@class=&quot;position-relative&quot;]/input[@class=&quot;btn btn-primary btn-block js-sign-in-button&quot;]</value>
      <webElementGuid>e17be1ec-6916-46b7-a01a-d9cb99f2889d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='commit']</value>
      <webElementGuid>06fcac5f-3fe5-4ece-a9fd-f1633b9064ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/div[4]/form/div/input[12]</value>
      <webElementGuid>eab360ca-5c69-44f8-8ded-32717b2735c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[12]</value>
      <webElementGuid>7a976df2-e13e-4e0a-bac3-af78af5ffb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'commit']</value>
      <webElementGuid>fdfbfbca-68ce-483a-a095-189398689a24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
